/**
 * Innosuisse.Startupticker.WebApp.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupingInfo } from './groupingInfo';
import { SortingInfo } from './sortingInfo';
import { SummaryInfo } from './summaryInfo';


export interface DataSourceLoadOptions { 
    requireTotalCount?: boolean;
    requireGroupCount?: boolean;
    isCountQuery?: boolean;
    isSummaryQuery?: boolean;
    skip?: number;
    take?: number;
    sort?: Array<SortingInfo> | null;
    group?: Array<GroupingInfo> | null;
    filter?: Array<any> | null;
    totalSummary?: Array<SummaryInfo> | null;
    groupSummary?: Array<SummaryInfo> | null;
    select?: Array<string> | null;
    preSelect?: Array<string> | null;
    remoteSelect?: boolean | null;
    remoteGrouping?: boolean | null;
    expandLinqSumType?: boolean | null;
    primaryKey?: Array<string> | null;
    defaultSort?: string | null;
    stringToLower?: boolean | null;
    paginateViaPrimaryKey?: boolean | null;
    sortByPrimaryKey?: boolean | null;
    allowAsyncOverSync?: boolean;
}

