/**
 * Innosuisse.Startupticker.WebApp.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GroupingInfo { 
    selector?: string | null;
    desc?: boolean;
    groupInterval?: string | null;
    isExpanded?: boolean | null;
}

