/**
 * Innosuisse.Startupticker.WebApp.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Startup } from './startup';


export interface StartupFundingRound { 
    id?: string;
    dealId: string | null;
    startupId?: string;
    investors?: string | null;
    amount?: number | null;
    valuation?: number | null;
    date?: string | null;
    startup?: Startup;
}

