/**
 * Innosuisse.Startupticker.WebApp.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Startup } from './startup';


export interface StartupTag { 
    startupId: string;
    name: string | null;
    startup?: Startup;
}

