/**
 * Innosuisse.Startupticker.WebApp.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StartupFundingRound } from './startupFundingRound';
import { StartupTag } from './startupTag';


export interface Startup { 
    id: string;
    source: string | null;
    name: string | null;
    description?: string | null;
    legalName?: string | null;
    industry?: string | null;
    countryCode?: string | null;
    country?: string | null;
    canton?: string | null;
    region?: string | null;
    city?: string | null;
    foundedOn?: string | null;
    foundedYear?: number | null;
    wasFunded?: boolean;
    fundingRoundsCount?: number | null;
    totalFunding?: number | null;
    lastValuation?: number | null;
    lastFundedOn?: string | null;
    isClosed?: boolean;
    closedAt?: string | null;
    embedding?: Array<number> | null;
    startupsFundingRounds?: Array<StartupFundingRound> | null;
    tags?: Array<StartupTag> | null;
}

