/**
 * Innosuisse.Startupticker.WebApp.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WeatherForecast { 
    date?: string;
    temperatureC?: number;
    readonly temperatureF?: number;
    summary?: string | null;
}

